spring.application.name=ComponentBidApi
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/Bidding
spring.datasource.username=postgres
spring.datasource.password=12345

logging.level.root=info

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#server.port=8081
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/Bidding
#spring.datasource.username=postgres
#spring.datasource.password=12345
#
#logging.level.root=info