spring.application.name=ComponentBidApi

spring.datasource.url=_REQUIRED_
spring.datasource.username=_REQUIRED_
spring.datasource.password=_REQUIRED_

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update