spring.application.name=ComponentBidApi
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/Bidding
spring.datasource.username=postgres
spring.datasource.password=12345

logging.level.root=info

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#spring.application.name=ComponentBidApi
#
#spring.datasource.url=_REQUIRED_
#spring.datasource.username=_REQUIRED_
#spring.datasource.password=_REQUIRED_
#
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update